/* native_backend.c — Native executable compiler backend for Snovalang. */
#ifndef _POSIX_C_SOURCE
#define _POSIX_C_SOURCE 200809L
#endif
#ifndef _DEFAULT_SOURCE
#define _DEFAULT_SOURCE
#endif

#include "native_backend.h"
#include "native_scope.h"
#include "driver_utils.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

/* Split whitespace-separated flags into argv slots. `storage` is mutated.
 * Returns 0 when the flag list does not fit. */
static int append_ws_args(char *storage, char **argv, int *argc, int max_argc) {
  if (!storage || !storage[0]) {
    return 1;
  }
  for (char *tok = strtok(storage, " \t"); tok; tok = strtok(NULL, " \t")) {
    if (*argc >= max_argc) {
      return 0;
    }
    argv[(*argc)++] = tok;
  }
  return 1;
}

static int sn_native_spawn_cc(const SnTargetInfo *target, const char *output_path,
                              const char *c_source_path, const char *inc_dir,
                              const char *lib_path) {
  char cflags_buf[256];
  char ldflags_buf[256];
  snprintf(cflags_buf, sizeof(cflags_buf), "%s", target->cflags);
  snprintf(ldflags_buf, sizeof(ldflags_buf), "%s", target->ldflags);

  char *argv[96];
  int argc = 0;
  argv[argc++] = (char *)target->c_compiler;
  if (!append_ws_args(cflags_buf, argv, &argc, 80)) {
    fprintf(stderr, "error: compiler flag list is too long\n");
    return -1;
  }
  if (inc_dir && inc_dir[0]) {
    argv[argc++] = "-I";
    argv[argc++] = (char *)inc_dir;
  }
  argv[argc++] = "-o";
  argv[argc++] = (char *)output_path;
  argv[argc++] = (char *)c_source_path;
  if (lib_path && lib_path[0]) {
    argv[argc++] = (char *)lib_path;
  }
  if (!append_ws_args(ldflags_buf, argv, &argc, 94)) {
    fprintf(stderr, "error: linker flag list is too long\n");
    return -1;
  }
  argv[argc] = NULL;
  return sn_driver_execv(argv);
}

int sn_native_compile(const SnBCUnit *bc, const SnTargetInfo *target,
                      const char *output_path) {
  if (!bc || !target || !output_path) {
    return 0;
  }

  sn_driver_ensure_parent_dir(output_path);

  char c_source_path[1024];
  snprintf(c_source_path, sizeof(c_source_path), "%s.runner.c", output_path);

  FILE *f = fopen(c_source_path, "w");
  if (!f) {
    fprintf(stderr, "error: cannot create temporary build source %s\n",
            c_source_path);
    return 0;
  }

  /* Emit self-contained C runtime with embedded bytecode, pulsar threading, and
   * async loop */
  fprintf(f, "/* Auto-generated by snovac native backend */\n");
  fprintf(f, "#define _POSIX_C_SOURCE 200809L\n");
  fprintf(f, "#define _DEFAULT_SOURCE\n");
  fprintf(f, "#include <stdio.h>\n");
  fprintf(f, "#include <stdlib.h>\n");
  fprintf(f, "#include <string.h>\n");
  fprintf(f, "#include <stdint.h>\n");
  fprintf(f, "#include <stdbool.h>\n");

  if (target->os == SN_OS_WINDOWS) {
    fprintf(f, "#include <windows.h>\n");
    fprintf(f, "#include <process.h>\n");
  } else {
    fprintf(f, "#include <pthread.h>\n");
    fprintf(f, "#include <unistd.h>\n");
  }
  fprintf(f, "\n");

  /* Emit Bytecode strings */
  fprintf(f, "static const char *g_strings[%zu] = {\n",
          bc->string_pool.count ? bc->string_pool.count : 1);
  for (size_t i = 0; i < bc->string_pool.count; i++) {
    fprintf(f, "  \"");
    for (const char *p = bc->string_pool.strings[i]; *p; p++) {
      if (*p == '"')
        fprintf(f, "\\\"");
      else if (*p == '\\')
        fprintf(f, "\\\\");
      else if (*p == '\n')
        fprintf(f, "\\n");
      else if (*p == '\t')
        fprintf(f, "\\t");
      else
        fputc(*p, f);
    }
    fprintf(f, "\",\n");
  }
  if (bc->string_pool.count == 0) {
    fprintf(f, "  \"\"\n");
  }
  fprintf(f, "};\n\n");

  /* Emit Bytecode functions */
  for (size_t i = 0; i < bc->function_count; i++) {
    SnFunctionChunk *fn = bc->functions[i];
    fprintf(f, "static const uint8_t g_fn_code_%zu[%zu] = {", i,
            fn->chunk.count ? fn->chunk.count : 1);
    for (size_t ci = 0; ci < fn->chunk.count; ci++) {
      if (ci % 16 == 0)
        fprintf(f, "\n  ");
      fprintf(f, "0x%02x, ", fn->chunk.code[ci]);
    }
    fprintf(f, "\n};\n");
  }

  /* Emit Value types and Stack */
  fprintf(f, "\n");
  fprintf(f, "typedef enum { VAL_UNIT, VAL_BOOL, VAL_INT, VAL_DOUBLE, "
             "VAL_STRING, VAL_ARRAY, VAL_OBJ, VAL_FUTURE, VAL_NULL, VAL_VAR } ValTag;\n");
  fprintf(f, "typedef struct Val Val;\n");
  fprintf(f, "struct Val { ValTag tag; union { bool b; int64_t i; double d; "
             "char *str; void *ptr; } as; };\n\n");
  fprintf(f, "#define SN_VAL_STACK_MAX 4096\n");
  fprintf(f, "static Val g_stack[SN_VAL_STACK_MAX];\n");
  fprintf(f, "static Val *g_sp = g_stack;\n");
  fprintf(f, "static inline void push(Val v) {\n");
  fprintf(f, "  if (g_sp >= g_stack + SN_VAL_STACK_MAX) {\n");
  fprintf(f, "    fputs(\"error: value stack overflow\\n\", stderr);\n");
  fprintf(f, "    exit(70);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  *g_sp++ = v;\n");
  fprintf(f, "}\n");
  fprintf(f, "static inline Val pop(void) {\n");
  fprintf(f, "  if (g_sp <= g_stack) {\n");
  fprintf(f, "    fputs(\"error: value stack underflow\\n\", stderr);\n");
  fprintf(f, "    exit(70);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  return *(--g_sp);\n");
  fprintf(f, "}\n");
  fprintf(f, "static inline Val peek(int d) { return g_sp[-1 - d]; }\n\n");

  fprintf(f, "static uint32_t read_u32(const uint8_t **ip) {\n");
  fprintf(f,
          "  uint32_t v = (uint32_t)((*ip)[0]) | ((uint32_t)((*ip)[1]) << 8) | "
          "((uint32_t)((*ip)[2]) << 16) | ((uint32_t)((*ip)[3]) << 24);\n");
  fprintf(f, "  *ip += 4;\n  return v;\n}\n");

  fprintf(f, "static int64_t read_i64(const uint8_t **ip) {\n");
  fprintf(f, "  uint64_t v = 0;\n  for (int i = 0; i < 8; i++) v |= "
             "((uint64_t)((*ip)[i]) << (i * 8));\n");
  fprintf(f, "  *ip += 8;\n  return (int64_t)v;\n}\n");

  fprintf(f, "static double read_double(const uint8_t **ip) {\n");
  fprintf(f, "  union { double d; uint64_t u; } cvt; cvt.u = 0;\n");
  fprintf(f, "  for (int i = 0; i < 8; i++) cvt.u |= ((uint64_t)((*ip)[i]) << "
             "(i * 8));\n");
  fprintf(f, "  *ip += 8;\n  return cvt.d;\n}\n\n");

  fprintf(f, "typedef struct SnArray { Val *items; uint32_t count; uint32_t cap; } SnArray;\n");
  fprintf(f, "typedef struct SnObj { Val *fields; uint32_t count; } SnObj;\n\n");
  fprintf(f, "static int val_truthy(Val cond) {\n");
  fprintf(f, "  if (cond.tag == VAL_BOOL) return cond.as.b != 0;\n");
  fprintf(f, "  if (cond.tag == VAL_INT) return cond.as.i != 0;\n");
  fprintf(f, "  return 0;\n}\n\n");
  fprintf(f, "static Val g_ret;\n\n");
  fprintf(f, "static void print_val(Val v, int nl) {\n");
  fprintf(f, "  if (v.tag == VAL_STRING) printf(\"%%s\", v.as.str ? v.as.str : \"\");\n");
  fprintf(f, "  else if (v.tag == VAL_INT) printf(\"%%lld\", (long long)v.as.i);\n");
  fprintf(f, "  else if (v.tag == VAL_DOUBLE) printf(\"%%g\", v.as.d);\n");
  fprintf(f, "  else if (v.tag == VAL_BOOL) printf(\"%%s\", v.as.b ? \"true\" : \"false\");\n");
  fprintf(f, "  else if (v.tag == VAL_NULL) printf(\"null\");\n");
  fprintf(f, "  else if (v.tag == VAL_ARRAY) {\n");
  fprintf(f, "    SnArray *a = (SnArray *)v.as.ptr;\n");
  fprintf(f, "    fputc('[', stdout);\n");
  fprintf(f, "    if (a && a->items) {\n");
  fprintf(f, "      for (uint32_t i = 0; i < a->count; i++) {\n");
  fprintf(f, "        if (i) printf(\", \");\n");
  fprintf(f, "        print_val(a->items[i], 0);\n");
  fprintf(f, "      }\n");
  fprintf(f, "    }\n");
  fprintf(f, "    fputc(']', stdout);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  if (nl) printf(\"\\n\");\n");
  fprintf(f, "}\n\n");
  fprintf(f, "static Val sn_read_bytes(const char *path) {\n");
  fprintf(f, "  FILE *fp = fopen(path ? path : \"\", \"rb\");\n");
  fprintf(f, "  if (!fp) {\n");
  fprintf(f, "    fprintf(stderr, \"error: cannot read '%%s'\\n\", path ? path : \"\");\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  size_t cap = 64, n = 0;\n");
  fprintf(f, "  unsigned char *buf = (unsigned char *)malloc(cap);\n");
  fprintf(f, "  if (!buf) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n");
  fprintf(f, "  int ch;\n");
  fprintf(f, "  while ((ch = fgetc(fp)) != EOF) {\n");
  fprintf(f, "    if (n == cap) {\n");
  fprintf(f, "      if (cap > (SIZE_MAX / 2)) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n");
  fprintf(f, "      cap *= 2;\n");
  fprintf(f, "      unsigned char *grown = (unsigned char *)realloc(buf, cap);\n");
  fprintf(f, "      if (!grown) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n");
  fprintf(f, "      buf = grown;\n");
  fprintf(f, "    }\n");
  fprintf(f, "    buf[n++] = (unsigned char)ch;\n");
  fprintf(f, "  }\n");
  fprintf(f, "  if (ferror(fp)) {\n");
  fprintf(f, "    fprintf(stderr, \"error: cannot read '%%s'\\n\", path ? path : \"\");\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  fclose(fp);\n");
  fprintf(f, "  if (n > UINT32_MAX) { fputs(\"error: file is too large\\n\", stderr); exit(1); }\n");
  fprintf(f, "  SnArray *a = (SnArray *)calloc(1, sizeof(SnArray));\n");
  fprintf(f, "  if (!a) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n");
  fprintf(f, "  a->count = (uint32_t)n;\n");
  fprintf(f, "  a->cap = (uint32_t)n;\n");
  fprintf(f, "  a->items = (Val *)calloc(n ? n : 1, sizeof(Val));\n");
  fprintf(f, "  if (!a->items) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n");
  fprintf(f, "  for (size_t i = 0; i < n; i++) {\n");
  fprintf(f, "    a->items[i].tag = VAL_INT;\n");
  fprintf(f, "    a->items[i].as.i = buf[i];\n");
  fprintf(f, "  }\n");
  fprintf(f, "  free(buf);\n");
  fprintf(f, "  Val v; memset(&v, 0, sizeof(v)); v.tag = VAL_ARRAY; v.as.ptr = a;\n");
  fprintf(f, "  return v;\n");
  fprintf(f, "}\n\n");
  fprintf(f, "static Val sn_write_bytes(const char *path, Val data) {\n");
  fprintf(f, "  if (!path || data.tag != VAL_ARRAY || !data.as.ptr) {\n");
  fprintf(f, "    fputs(\"error: write_bytes expects a path and an int array\\n\", stderr);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  SnArray *a = (SnArray *)data.as.ptr;\n");
  fprintf(f, "  FILE *fp = fopen(path, \"wb\");\n");
  fprintf(f, "  if (!fp) {\n");
  fprintf(f, "    fprintf(stderr, \"error: cannot write '%%s'\\n\", path);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  for (uint32_t i = 0; i < a->count; i++) {\n");
  fprintf(f, "    long long nbyte = a->items[i].as.i;\n");
  fprintf(f, "    if (fputc((int)(nbyte & 0xff), fp) == EOF) {\n");
  fprintf(f, "      fprintf(stderr, \"error: cannot write '%%s'\\n\", path);\n");
  fprintf(f, "      exit(1);\n");
  fprintf(f, "    }\n");
  fprintf(f, "  }\n");
  fprintf(f, "  if (fclose(fp) != 0) {\n");
  fprintf(f, "    fprintf(stderr, \"error: cannot write '%%s'\\n\", path);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  Val u; memset(&u, 0, sizeof(u)); u.tag = VAL_UNIT;\n");
  fprintf(f, "  return u;\n");
  fprintf(f, "}\n\n");
  fprintf(f, "static Val sn_array_len(Val arr) {\n");
  fprintf(f, "  if (arr.tag != VAL_ARRAY || !arr.as.ptr) {\n");
  fprintf(f, "    fputs(\"error: len expects an array\\n\", stderr);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  Val r; memset(&r, 0, sizeof(r)); r.tag = VAL_INT;\n");
  fprintf(f, "  r.as.i = (int64_t)((SnArray *)arr.as.ptr)->count;\n");
  fprintf(f, "  return r;\n");
  fprintf(f, "}\n\n");
  fprintf(f, "static Val sn_array_push(Val arr, Val item) {\n");
  fprintf(f, "  if (arr.tag != VAL_ARRAY || !arr.as.ptr) {\n");
  fprintf(f, "    fputs(\"error: push expects an array\\n\", stderr);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  SnArray *a = (SnArray *)arr.as.ptr;\n");
  fprintf(f, "  if (a->count == a->cap) {\n");
  fprintf(f, "    if (a->cap > (UINT32_MAX / 2u)) {\n");
  fprintf(f, "      fputs(\"error: out of memory\\n\", stderr); exit(1);\n");
  fprintf(f, "    }\n");
  fprintf(f, "    uint32_t cap = a->cap < 4u ? 4u : a->cap * 2u;\n");
  fprintf(f, "    Val *grown = (Val *)realloc(a->items, (size_t)cap * sizeof(Val));\n");
  fprintf(f, "    if (!grown) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n");
  fprintf(f, "    a->items = grown;\n");
  fprintf(f, "    a->cap = cap;\n");
  fprintf(f, "  }\n");
  fprintf(f, "  a->items[a->count] = item;\n");
  fprintf(f, "  a->count += 1u;\n");
  fprintf(f, "  Val r; memset(&r, 0, sizeof(r)); r.tag = VAL_INT; r.as.i = (int64_t)a->count;\n");
  fprintf(f, "  return r;\n");
  fprintf(f, "}\n\n");

  /* Emit Pulsar Multi-parallelism Runtime */
  fprintf(f, "/* Pulsar platform thread multi-parallelism */\n");
  fprintf(f, "typedef struct PulsarWork {\n");
  fprintf(f, "  size_t fn_idx;\n");
  fprintf(f, "  Val args[8];\n");
  fprintf(f, "  uint32_t argc;\n");
  fprintf(f, "  struct PulsarWork *next;\n");
  fprintf(f, "} PulsarWork;\n\n");

  if (target->os == SN_OS_WINDOWS) {
    fprintf(f, "static CRITICAL_SECTION g_pulsar_mutex;\n");
    fprintf(f, "static CONDITION_VARIABLE g_pulsar_cond;\n");
  } else {
    fprintf(
        f,
        "static pthread_mutex_t g_pulsar_mutex = PTHREAD_MUTEX_INITIALIZER;\n");
    fprintf(
        f, "static pthread_cond_t g_pulsar_cond = PTHREAD_COND_INITIALIZER;\n");
  }
  fprintf(f, "static PulsarWork *g_pulsar_queue = NULL;\n");
  fprintf(f, "static int g_pulsar_busy = 0;\n");
  fprintf(f, "static bool g_pulsar_stop = false;\n\n");

  fprintf(f, "static int run_function(size_t fn_idx, const Val *args, uint32_t argc);\n\n");

  if (target->os == SN_OS_WINDOWS) {
    fprintf(f, "static unsigned __stdcall pulsar_thread_proc(void *arg) {\n");
    fprintf(f, "  (void)arg;\n");
    fprintf(f, "  for (;;) {\n");
    fprintf(f, "    EnterCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "    while (!g_pulsar_queue && !g_pulsar_stop) {\n");
    fprintf(f, "      SleepConditionVariableCS(&g_pulsar_cond, "
               "&g_pulsar_mutex, INFINITE);\n");
    fprintf(f, "    }\n");
    fprintf(f, "    if (g_pulsar_stop && !g_pulsar_queue) { "
               "LeaveCriticalSection(&g_pulsar_mutex); break; }\n");
    fprintf(f, "    PulsarWork *work = g_pulsar_queue;\n");
    fprintf(f, "    if (work) { g_pulsar_queue = work->next; g_pulsar_busy = 1; }\n");
    fprintf(f, "    LeaveCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "    if (work) {\n");
    fprintf(f, "      run_function(work->fn_idx, work->args, work->argc);\n");
    fprintf(f, "      EnterCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "      g_pulsar_busy = 0;\n");
    fprintf(f, "      WakeConditionVariable(&g_pulsar_cond);\n");
    fprintf(f, "      LeaveCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "      free(work);\n");
    fprintf(f, "    }\n");
    fprintf(f, "  }\n  return 0;\n}\n\n");
  } else {
    fprintf(f, "static void *pulsar_thread_proc(void *arg) {\n");
    fprintf(f, "  (void)arg;\n");
    fprintf(f, "  for (;;) {\n");
    fprintf(f, "    pthread_mutex_lock(&g_pulsar_mutex);\n");
    fprintf(f, "    while (!g_pulsar_queue && !g_pulsar_stop) {\n");
    fprintf(f, "      pthread_cond_wait(&g_pulsar_cond, &g_pulsar_mutex);\n");
    fprintf(f, "    }\n");
    fprintf(f, "    if (g_pulsar_stop && !g_pulsar_queue) { "
               "pthread_mutex_unlock(&g_pulsar_mutex); break; }\n");
    fprintf(f, "    PulsarWork *work = g_pulsar_queue;\n");
    fprintf(f, "    if (work) { g_pulsar_queue = work->next; g_pulsar_busy = 1; }\n");
    fprintf(f, "    pthread_mutex_unlock(&g_pulsar_mutex);\n");
    fprintf(f, "    if (work) {\n");
    fprintf(f, "      run_function(work->fn_idx, work->args, work->argc);\n");
    fprintf(f, "      pthread_mutex_lock(&g_pulsar_mutex);\n");
    fprintf(f, "      g_pulsar_busy = 0;\n");
    fprintf(f, "      pthread_cond_signal(&g_pulsar_cond);\n");
    fprintf(f, "      pthread_mutex_unlock(&g_pulsar_mutex);\n");
    fprintf(f, "      free(work);\n");
    fprintf(f, "    }\n");
    fprintf(f, "  }\n  return NULL;\n}\n\n");
  }

  fprintf(f, "static void pulsar_spawn(size_t fn_idx) {\n");
  fprintf(f, "  PulsarWork *work = (PulsarWork*)malloc(sizeof(PulsarWork));\n");
  fprintf(f, "  if (!work) { fputs(\"error: out of memory\\n\", stderr); exit(70); }\n");
  fprintf(f, "  work->fn_idx = fn_idx;\n  work->argc = 0;\n  work->next = NULL;\n");
  if (target->os == SN_OS_WINDOWS) {
    fprintf(f, "  EnterCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "  work->next = g_pulsar_queue;\n  g_pulsar_queue = work;\n");
    fprintf(f, "  WakeConditionVariable(&g_pulsar_cond);\n");
    fprintf(f, "  LeaveCriticalSection(&g_pulsar_mutex);\n");
  } else {
    fprintf(f, "  pthread_mutex_lock(&g_pulsar_mutex);\n");
    fprintf(f, "  work->next = g_pulsar_queue;\n  g_pulsar_queue = work;\n");
    fprintf(f, "  pthread_cond_signal(&g_pulsar_cond);\n");
    fprintf(f, "  pthread_mutex_unlock(&g_pulsar_mutex);\n");
  }
  fprintf(f, "}\n\n");

  sn_native_write_scope_support(f, target->os == SN_OS_WINDOWS);

  /* Emit run_function */
  fprintf(f, "static int run_function(size_t fn_idx, const Val *args, uint32_t argc) {\n");
  fprintf(f, "  const uint8_t *code = NULL;\n");
  for (size_t i = 0; i < bc->function_count; i++) {
    fprintf(f, "  if (fn_idx == %zu) code = g_fn_code_%zu;\n", i, i);
  }
  fprintf(f, "  if (!code) {\n");
  fprintf(f, "    fputs(\"error: unknown function\\n\", stderr);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  const uint8_t *ip = code;\n");
  fprintf(f, "  Val locals[256]; memset(locals, 0, sizeof(locals));\n");
  fprintf(f, "  if (argc > 256) {\n");
  fprintf(f, "    fputs(\"error: too many arguments\\n\", stderr);\n");
  fprintf(f, "    exit(1);\n");
  fprintf(f, "  }\n");
  fprintf(f, "  if (args) {\n");
  fprintf(f, "    for (uint32_t i = 0; i < argc; i++) locals[i] = args[i];\n");
  fprintf(f, "  }\n");
  fprintf(f, "  g_ret.tag = VAL_UNIT; g_ret.as.i = 0;\n");
  fprintf(f, "  DeferItem *defers = NULL;\n");
  fprintf(f, "  for (;;) {\n");
  fprintf(f, "    uint8_t op = *ip++;\n");
  fprintf(f, "    switch (op) {\n");
  fprintf(f, "    case %d: break;\n", OP_NOP);
  fprintf(f,
          "    case %d: { Val v; v.tag = VAL_INT; v.as.i = read_i64(&ip); "
          "push(v); break; }\n",
          OP_CONST_INT);
  fprintf(f,
          "    case %d: { Val v; v.tag = VAL_DOUBLE; v.as.d = "
          "read_double(&ip); push(v); break; }\n",
          OP_CONST_DOUBLE);
  fprintf(f,
          "    case %d: { Val v; v.tag = VAL_STRING; v.as.str = "
          "(char*)g_strings[read_u32(&ip)]; push(v); break; }\n",
          OP_CONST_STRING);
  fprintf(f,
          "    case %d: { Val v; v.tag = VAL_BOOL; v.as.b = *ip++ != 0; "
          "push(v); break; }\n",
          OP_CONST_BOOL);
  fprintf(
      f,
      "    case %d: { Val v; v.tag = VAL_UNIT; v.as.i = 0; push(v); break; }\n",
      OP_CONST_UNIT);
  fprintf(f, "    case %d: pop(); break;\n", OP_POP);
  fprintf(f, "    case %d: push(peek(0)); break;\n", OP_DUP);
  fprintf(
      f,
      "    case %d: { uint32_t s = read_u32(&ip); push(locals[s]); break; }\n",
      OP_GET_LOCAL);
  fprintf(f,
          "    case %d: { uint32_t s = read_u32(&ip); locals[s] = peek(0); "
          "break; }\n",
          OP_SET_LOCAL);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r;\n"
          "      if (a.tag == VAL_STRING && b.tag == VAL_STRING) {\n"
          "        size_t la = strlen(a.as.str), lb = strlen(b.as.str);\n"
          "        if (lb > ((size_t)-1) - la - 1) {\n"
          "          fputs(\"error: string concat overflow\\n\", stderr); exit(70);\n"
          "        }\n"
          "        char *buf = malloc(la + lb + 1);\n"
          "        if (!buf) { fputs(\"error: out of memory\\n\", stderr); exit(70); }\n"
          "        memcpy(buf, a.as.str, la); memcpy(buf + la, b.as.str, lb); buf[la + lb] = 0;\n"
          "        r.tag = VAL_STRING; r.as.str = buf;\n"
          "      } else if (a.tag == VAL_DOUBLE || b.tag == VAL_DOUBLE) {\n"
          "        r.tag = VAL_DOUBLE; r.as.d = (a.tag == VAL_DOUBLE ? a.as.d "
          ": a.as.i) + (b.tag == VAL_DOUBLE ? b.as.d : b.as.i);\n"
          "      } else {\n"
          "        r.tag = VAL_INT; r.as.i = a.as.i + b.as.i;\n"
          "      }\n      push(r); break;\n    }\n",
          OP_ADD);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i "
          "= a.as.i - b.as.i; push(r); break; }\n",
          OP_SUB);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i "
          "= a.as.i * b.as.i; push(r); break; }\n",
          OP_MUL);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i "
          "= b.as.i ? a.as.i / b.as.i : 0; push(r); break; }\n",
          OP_DIV);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_INT; r.as.i "
          "= b.as.i ? a.as.i %% b.as.i : 0; push(r); break; }\n",
          OP_MOD);
  fprintf(f,
          "    case %d: { Val a = pop(), r; r.tag = VAL_INT; r.as.i = -a.as.i; "
          "push(r); break; }\n",
          OP_NEG);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; memset(&r, 0, sizeof(r)); "
          "r.tag = VAL_INT; r.as.i = a.as.i & b.as.i; push(r); break; }\n",
          OP_BIT_AND);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; memset(&r, 0, sizeof(r)); "
          "r.tag = VAL_INT; r.as.i = a.as.i | b.as.i; push(r); break; }\n",
          OP_BIT_OR);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; memset(&r, 0, sizeof(r)); "
          "r.tag = VAL_INT; r.as.i = a.as.i ^ b.as.i; push(r); break; }\n",
          OP_BIT_XOR);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; memset(&r, 0, sizeof(r)); "
          "r.tag = VAL_INT; r.as.i = (int64_t)((uint64_t)a.as.i << (b.as.i & 63)); "
          "push(r); break; }\n",
          OP_SHL);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; memset(&r, 0, sizeof(r)); "
          "r.tag = VAL_INT; r.as.i = a.as.i >> (b.as.i & 63); push(r); break; }\n",
          OP_SHR);
  fprintf(f,
          "    case %d: { Val a = pop(), r; memset(&r, 0, sizeof(r)); r.tag = VAL_BOOL; "
          "r.as.b = !val_truthy(a); push(r); break; }\n",
          OP_NOT);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; "
          "r.as.b = (a.tag != VAL_NULL && b.tag != VAL_NULL && a.as.i == b.as.i); "
          "push(r); break; }\n",
          OP_EQ);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; "
          "r.as.b = (a.tag == VAL_NULL || b.tag == VAL_NULL || a.as.i != b.as.i); "
          "push(r); break; }\n",
          OP_NE);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; "
          "r.as.b = (a.as.i < b.as.i); push(r); break; }\n",
          OP_LT);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; "
          "r.as.b = (a.as.i <= b.as.i); push(r); break; }\n",
          OP_LE);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; "
          "r.as.b = (a.as.i > b.as.i); push(r); break; }\n",
          OP_GT);
  fprintf(f,
          "    case %d: { Val b = pop(), a = pop(), r; r.tag = VAL_BOOL; "
          "r.as.b = (a.as.i >= b.as.i); push(r); break; }\n",
          OP_GE);
  fprintf(f,
          "    case %d: { int32_t off = (int32_t)read_u32(&ip); ip += off; "
          "break; }\n",
          OP_JUMP);
  fprintf(f,
          "    case %d: { int32_t off = (int32_t)read_u32(&ip); Val cond = pop(); "
          "if (!val_truthy(cond)) ip += off; break; }\n",
          OP_JUMP_IF_FALSE);
  fprintf(f,
          "    case %d: { int32_t off = (int32_t)read_u32(&ip); Val cond = pop(); "
          "if (val_truthy(cond)) ip += off; break; }\n",
          OP_JUMP_IF_TRUE);
  fprintf(f,
          "    case %d: { uint32_t fni = read_u32(&ip); uint32_t argc = read_u32(&ip);\n"
          "      if (argc > 256) { fputs(\"error: too many arguments\\n\", stderr); exit(1); }\n"
          "      Val args_tmp[256]; memset(args_tmp, 0, sizeof(args_tmp));\n"
          "      for (uint32_t ai = argc; ai > 0; ai--) args_tmp[ai - 1] = pop();\n"
          "      run_function(fni, args_tmp, argc); push(g_ret); break; }\n",
          OP_CALL);
  fprintf(f,
          "    case %d: { Val saved = pop(); run_defers(&defers); g_ret = saved; return 0; }\n",
          OP_RETURN);
  fprintf(f,
          "    case %d: { uint32_t cls = read_u32(&ip); uint32_t n = read_u32(&ip); (void)cls;\n"
          "      SnObj *o = (SnObj *)calloc(1, sizeof(SnObj));\n"
          "      if (!o) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n"
          "      o->count = n;\n"
          "      o->fields = (Val *)calloc(n ? n : 1, sizeof(Val));\n"
          "      if (!o->fields) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n"
          "      for (uint32_t i = n; i > 0; i--) o->fields[i - 1] = pop();\n"
          "      Val v; memset(&v, 0, sizeof(v)); v.tag = VAL_OBJ; v.as.ptr = o; push(v); break; }\n",
          OP_NEW_OBJ);
  fprintf(f,
          "    case %d: { uint32_t idx = read_u32(&ip); Val obj = pop();\n"
          "      SnObj *o = (obj.tag == VAL_OBJ) ? (SnObj *)obj.as.ptr : NULL;\n"
          "      if (!o || idx >= o->count) { fputs(\"error: field index out of bounds\\n\", stderr); exit(1); }\n"
          "      push(o->fields[idx]); break; }\n",
          OP_GET_FIELD);
  fprintf(f,
          "    case %d: { uint32_t idx = read_u32(&ip); Val obj = pop(); Val v = peek(0);\n"
          "      SnObj *o = (obj.tag == VAL_OBJ) ? (SnObj *)obj.as.ptr : NULL;\n"
          "      if (!o || idx >= o->count) { fputs(\"error: field index out of bounds\\n\", stderr); exit(1); }\n"
          "      o->fields[idx] = v; break; }\n",
          OP_SET_FIELD);
  fprintf(f,
          "    case %d: { uint32_t n = read_u32(&ip);\n"
          "      SnArray *a = (SnArray *)calloc(1, sizeof(SnArray));\n"
          "      if (!a) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n"
          "      a->count = n;\n"
          "      a->cap = n;\n"
          "      a->items = (Val *)calloc(n ? n : 1, sizeof(Val));\n"
          "      if (!a->items) { fputs(\"error: out of memory\\n\", stderr); exit(1); }\n"
          "      for (uint32_t i = n; i > 0; i--) a->items[i - 1] = pop();\n"
          "      Val v; memset(&v, 0, sizeof(v)); v.tag = VAL_ARRAY; v.as.ptr = a; push(v); break; }\n",
          OP_NEW_ARRAY);
  fprintf(f,
          "    case %d: { Val idx = pop(); Val arr = pop();\n"
          "      SnArray *a = (arr.tag == VAL_ARRAY) ? (SnArray *)arr.as.ptr : NULL;\n"
          "      if (!a || idx.tag != VAL_INT || idx.as.i < 0 || (uint64_t)idx.as.i >= a->count) {\n"
          "        fputs(\"error: array index out of bounds\\n\", stderr); exit(1);\n"
          "      }\n"
          "      push(a->items[(uint32_t)idx.as.i]); break; }\n",
          OP_GET_INDEX);
  fprintf(f,
          "    case %d: { Val path = pop();\n"
          "      if (path.tag != VAL_STRING) { fputs(\"error: read_bytes expects a string path\\n\", stderr); exit(1); }\n"
          "      push(sn_read_bytes(path.as.str)); break; }\n",
          OP_READ_BYTES);
  fprintf(f,
          "    case %d: { Val data = pop(); Val path = pop();\n"
          "      if (path.tag != VAL_STRING) { fputs(\"error: write_bytes expects a string path\\n\", stderr); exit(1); }\n"
          "      push(sn_write_bytes(path.as.str, data)); break; }\n",
          OP_WRITE_BYTES);
  fprintf(f,
          "    case %d: { push(sn_array_len(pop())); break; }\n",
          OP_ARRAY_LEN);
  fprintf(f,
          "    case %d: { Val item = pop(); Val arr = pop(); push(sn_array_push(arr, item)); break; }\n",
          OP_ARRAY_PUSH);
  fprintf(f,
          "    case %d: { uint8_t nl = *ip++; Val v = pop(); print_val(v, nl); break; }\n",
          OP_PRINT);
  fprintf(f, "    case %d: g_ret.tag = VAL_INT; g_ret.as.i = 0; return 0;\n", OP_HALT);
  sn_native_write_scope_ops(f, target->os == SN_OS_WINDOWS);
  fprintf(f, "    default: fprintf(stderr, \"error: unknown opcode %%u\\n\", (unsigned)op); exit(1);\n");
  fprintf(f, "    }\n  }\n}\n\n");

  /* Main entry */
  fprintf(f, "int main(int argc, char **argv) {\n");
  fprintf(f, "  (void)argc; (void)argv;\n");
  if (target->os == SN_OS_WINDOWS) {
    fprintf(f, "  InitializeCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "  InitializeConditionVariable(&g_pulsar_cond);\n");
  } else {
    fprintf(f, "  pthread_t pth;\n");
    fprintf(f, "  pthread_create(&pth, NULL, pulsar_thread_proc, NULL);\n");
  }
  fprintf(f, "  run_function(%u, NULL, 0);\n", bc->main_func_idx);
  fprintf(f, "  int rc = (g_ret.tag == VAL_INT) ? (int)g_ret.as.i : 0;\n");
  if (target->os == SN_OS_WINDOWS) {
    fprintf(f, "  EnterCriticalSection(&g_pulsar_mutex);\n");
    fprintf(f, "  g_pulsar_stop = true;\n");
    fprintf(f, "  WakeConditionVariable(&g_pulsar_cond);\n");
    fprintf(f, "  LeaveCriticalSection(&g_pulsar_mutex);\n");
  } else {
    fprintf(f, "  pthread_mutex_lock(&g_pulsar_mutex);\n");
    fprintf(f, "  g_pulsar_stop = true;\n");
    fprintf(f, "  pthread_cond_broadcast(&g_pulsar_cond);\n");
    fprintf(f, "  pthread_mutex_unlock(&g_pulsar_mutex);\n");
    fprintf(f, "  pthread_join(pth, NULL);\n");
  }
  fprintf(f, "  return rc;\n");
  fprintf(f, "}\n");

  fclose(f);

  /* Compile runner C code to final binary using target compiler & flags */
  int status = sn_native_spawn_cc(target, output_path, c_source_path, NULL, NULL);
  remove(c_source_path);
  if (status != 0) {
    fprintf(stderr,
            "error: compilation to native binary failed with exit status %d\n",
            status);
    return 0;
  }

#ifndef _WIN32
  chmod(output_path, 0755);
#endif
  return 1;
}

int sn_native_compile_runtime(const SnPackageGraph *graph,
                              const SnTargetInfo *target,
                              const char *output_path) {
  if (!graph || !target || !output_path)
    return 0;

  sn_driver_ensure_parent_dir(output_path);

  char c_source_path[1024];
  snprintf(c_source_path, sizeof(c_source_path), "%s.rt.c", output_path);

  FILE *f = fopen(c_source_path, "w");
  if (!f) {
    fprintf(stderr, "error: cannot create temporary runtime source %s\n",
            c_source_path);
    return 0;
  }

  fprintf(f, "/* Auto-generated standalone binary with embedded Snovalang "
             "runtime */\n");
  fprintf(f, "#define _POSIX_C_SOURCE 200809L\n");
  fprintf(f, "#define _DEFAULT_SOURCE\n");
  fprintf(f, "#include <stdio.h>\n");
  fprintf(f, "#include <stdlib.h>\n");
  fprintf(f, "#include <string.h>\n");
  fprintf(f, "#include \"arena.h\"\n");
  fprintf(f, "#include \"diag.h\"\n");
  fprintf(f, "#include \"eval.h\"\n");
  fprintf(f, "#include \"lex.h\"\n");
  fprintf(f, "#include \"parse.h\"\n\n");

  size_t file_count = 0;
  for (SnPackageNode *node = graph->nodes; node; node = node->next) {
    for (SnPackageFile *pf = node->files; pf; pf = pf->next) {
      file_count++;
    }
  }

  size_t file_idx = 0;
  for (SnPackageNode *node = graph->nodes; node; node = node->next) {
    for (SnPackageFile *pf = node->files; pf; pf = pf->next, file_idx++) {
      fprintf(f, "static const char g_file_src_%zu[] = {", file_idx);
      for (size_t ci = 0; ci < pf->src_len; ci++) {
        if (ci % 20 == 0)
          fprintf(f, "\n  ");
        fprintf(f, "%d, ", (unsigned char)pf->src[ci]);
      }
      fprintf(f, "0\n};\n\n");
    }
  }

  fprintf(f, "typedef struct { const char *path; const char *src; size_t len; "
             "} EmbeddedFile;\n");
  fprintf(f, "static const EmbeddedFile g_embedded_files[%zu] = {\n",
          file_count ? file_count : 1);
  file_idx = 0;
  for (SnPackageNode *node = graph->nodes; node; node = node->next) {
    for (SnPackageFile *pf = node->files; pf; pf = pf->next, file_idx++) {
      fprintf(f, "  { \"%s\", g_file_src_%zu, %zu },\n",
              pf->path ? pf->path : "", file_idx, pf->src_len);
    }
  }
  if (file_count == 0) {
    fprintf(f, "  { \"\", \"\", 0 }\n");
  }
  fprintf(f, "};\n\n");

  fprintf(f, "int main(int argc, char **argv) {\n");
  fprintf(f, "  (void)argc; (void)argv;\n");
  fprintf(f, "  SnArena arena;\n");
  fprintf(f, "  sn_arena_init(&arena, 8 * 1024 * 1024);\n");
  fprintf(f, "  SnDiagSink diag;\n");
  fprintf(f, "  sn_diag_init(&diag, \"main\", \"\", 0);\n\n");
  fprintf(f, "  SnUnit merged;\n");
  fprintf(f, "  memset(&merged, 0, sizeof(merged));\n\n");
  fprintf(f, "  for (size_t i = 0; i < %zu; i++) {\n", file_count);
  fprintf(f, "    SnDiagFile self = { g_embedded_files[i].path, "
             "g_embedded_files[i].src, g_embedded_files[i].len };\n");
  fprintf(f, "    SnDiagFile outer = sn_diag_set_file(&diag, self);\n");
  fprintf(f, "    SnTokenVec toks;\n");
  fprintf(f, "    sn_lex(&arena, &diag, g_embedded_files[i].src, "
             "g_embedded_files[i].len, &toks);\n");
  fprintf(f, "    SnUnit unit;\n");
  fprintf(f, "    sn_parse(&arena, &diag, &toks, &unit);\n");
  fprintf(f, "    for (size_t di = 0; di < unit.decls.len; di++) {\n");
  fprintf(f, "      SnDecl *d = SN_LIST_AT(unit.decls, SnDecl, di);\n");
  fprintf(f, "      if (d && d->kind == SN_DECL_FUNC && strcmp(d->name, \"main\") == 0) {\n");
  fprintf(f, "        if (strstr(g_embedded_files[i].path, \".snovalang/deps\") != NULL ||\n");
  fprintf(f, "            strstr(g_embedded_files[i].path, \"snova-std\") != NULL) {\n");
  fprintf(f, "          continue; /* Skip library dependency's test main() */\n");
  fprintf(f, "        }\n");
  fprintf(f, "      }\n");
  fprintf(f, "      sn_list_push(&arena, &merged.decls, unit.decls.items[di]);\n");
  fprintf(f, "    }\n");
  fprintf(f, "    sn_diag_set_file(&diag, outer);\n");
  fprintf(f, "  }\n\n");
  fprintf(f, "  sn_eval_merge_extensions(&arena, &merged);\n");
  fprintf(f, "  int rc = sn_eval_run(&arena, &diag, &merged);\n");
  fprintf(f, "  sn_arena_free(&arena);\n");
  fprintf(f, "  return (rc < 0) ? 1 : rc;\n");
  fprintf(f, "}\n");

  fclose(f);

  /* Locate the runtime static lib + headers next to the running binary,
   * trying every layout snovac can plausibly be found in:
   *   - installed:    <prefix>/bin/snl, <prefix>/lib/libsnovart.a,
   *                   <prefix>/include/ (see "make install")
   *   - dev build:    snovac/build/snovac, snovac/build/libsnovart.a,
   *                   headers directly under snovac/
   *   - cwd fallback: used only if sn_driver_exe_dir could not be determined at all
   *                   (see sn_driver_set_exe_dir in driver_utils.c). */
  char inc_dir[1024];
  char lib_path[1024];

  const char *env_home = getenv("SNOVA_HOME");
  if (env_home && env_home[0]) {
    snprintf(inc_dir, sizeof(inc_dir), "%s/include", env_home);
    snprintf(lib_path, sizeof(lib_path), "%s/lib/libsnovart.a", env_home);
  } else if (sn_driver_exe_dir[0]) {
    /* Check sibling snovart directory first for local development */
    snprintf(inc_dir, sizeof(inc_dir), "%s/../../snovart/include", sn_driver_exe_dir);
    snprintf(lib_path, sizeof(lib_path), "%s/../../snovart/build/libsnovart.a", sn_driver_exe_dir);

    if (!sn_driver_path_is_file(lib_path) || !sn_driver_path_is_dir(inc_dir)) {
      /* Installed layout: <prefix>/bin/snl -> <prefix>/include, <prefix>/lib/libsnovart.a */
      snprintf(inc_dir, sizeof(inc_dir), "%s/../include", sn_driver_exe_dir);
      snprintf(lib_path, sizeof(lib_path), "%s/../lib/libsnovart.a", sn_driver_exe_dir);

      if (!sn_driver_path_is_file(lib_path) || !sn_driver_path_is_dir(inc_dir)) {
        /* Dev build layout: exe sits in snovac/build/ */
        snprintf(inc_dir, sizeof(inc_dir), "%s/..", sn_driver_exe_dir);
        snprintf(lib_path, sizeof(lib_path), "%s/libsnovart.a", sn_driver_exe_dir);
        if (!sn_driver_path_is_file(lib_path)) {
          snprintf(lib_path, sizeof(lib_path), "%s/build/libsnovart.a", inc_dir);
        }
      }
    }
  } else {
    snprintf(inc_dir, sizeof(inc_dir), "../snovart/include");
    snprintf(lib_path, sizeof(lib_path), "../snovart/build/libsnovart.a");
    if (!sn_driver_path_is_file(lib_path)) {
      snprintf(inc_dir, sizeof(inc_dir), ".");
      snprintf(lib_path, sizeof(lib_path), "build/libsnovart.a");
    }
  }

  int status = sn_native_spawn_cc(target, output_path, c_source_path, inc_dir,
                                 lib_path);
  remove(c_source_path);
  if (status != 0) {
    fprintf(stderr,
            "error: compilation of standalone runtime binary failed with exit "
            "status %d\n",
            status);
    return 0;
  }

#ifndef _WIN32
  chmod(output_path, 0755);
#endif
  return 1;
}
